### PR TITLE
Release/1.2

### PR DESCRIPTION
**Pull request by tommoser**

### CODE REVIEW

**Comment by KaushalKhamar** [comment]
Enum **DataState** not found in **Microsoft.InformationProtection**

Can you please check?

**Comment by tommoser** [comment]
> Enum **DataState** not found in **Microsoft.InformationProtection**
> 
> Can you please check?

We haven't released 1.2, yet. This is just a PR prepping for hte release next week. Try it out Tuesday next week and it'll work :)

**Comment by KaushalKhamar** [comment]
Hay thanks for update :)

**Comment by tommoser** [comment]
The updated packages are now avaiable on NuGet!

**Comment by KaushalKhamar** [comment]
Hay @tommoser 

Thank you so much for update. Much appreciated.

**Pull request merged**
